/**
 * types.ts — Shared TypeScript type definitions for the entire app.
 *
 * All data shapes that flow between components and the n8n AI pipeline
 * are defined here so TypeScript can catch mismatches at compile time.
 */

/**
 * ATS triage category (1 = most urgent, 5 = least urgent).
 * Based on the Australian Triage Scale used in all Australian EDs.
 *   CAT 1 — Resuscitation  (immediate)
 *   CAT 2 — Emergency      (within 10 min)
 *   CAT 3 — Urgent         (within 30 min)
 *   CAT 4 — Semi-Urgent    (within 60 min)
 *   CAT 5 — Non-Urgent     (within 120 min)
 */
export type TriageCategory = 1 | 2 | 3 | 4 | 5;

/**
 * Which main panel is currently visible in the centre column.
 * Controlled by PatientPanel's nav buttons; state lives in Dashboard.
 */
export type ActiveView = 'pipeline' | 'patientFlow' | 'analytics' | 'settings';

/**
 * A single completed simulation stored in localStorage for analytics.
 * Saved once the Decision Agent produces a final disposition.
 */
export interface SimulationRun {
  id: string;                  // unique ID generated by uid()
  timestamp: string;           // ISO date string
  patientName: string;
  disposition: DispositionLabel;
  triageCategory: TriageCategory;
}

/** How the patient arrived at the ED. */
export type ArrivalMode = 'Walk-in' | 'Ambulance' | 'GP Referral' | 'Self-referral';

/**
 * Status of a single agent card in the Pipeline panel.
 *   waiting — not yet started
 *   pending — queued (previous agent just finished)
 *   active  — currently "thinking" (animated spinner)
 *   done    — output received and displayed
 */
export type AgentStatus = 'waiting' | 'pending' | 'active' | 'done';

/** The three possible final outcomes the Decision Agent can choose. */
export type DispositionLabel = 'Admit to Hospital' | 'Short Stay Unit' | 'Discharge Home';

/**
 * All patient data collected in the New Simulation modal and sent as
 * the POST body to the n8n webhook. n8n passes this object to the
 * first AI agent (Patient Agent) and threads it through the pipeline.
 */
export interface PatientInput {
  name: string;
  age: number;
  sex: 'M' | 'F';
  arrivalMode: ArrivalMode;
  chiefComplaint: string;   // free-text presenting complaint

  // Vital signs — displayed in PatientPanel with warning colours if abnormal
  hr: number;    // heart rate (bpm)        — warn if < 60 or > 100
  rr: number;    // respiratory rate (/min) — warn if < 12 or > 20
  sbp: number;   // systolic blood pressure — warn if < 100 or > 160
  dbp: number;   // diastolic blood pressure
  temp: number;  // temperature (°C)        — warn if < 36 or > 38
  spo2: number;  // oxygen saturation (%)   — warn if < 95

  pmhx: string;     // past medical history
  meds: string;     // current medications
  allergies: string;
}

/**
 * The full output from all 5 AI agents, returned as one JSON object
 * by n8n's Respond to Webhook node at the end of the pipeline.
 *
 * Each key is optional because the simulation builds incrementally —
 * agents are revealed one at a time in the UI animation loop.
 */
export interface AgentOutputMap {
  /** Patient Agent — formats demographics and complaint into clinical language. */
  patientAgent?: {
    summary: string;      // one-sentence clinical summary
    demographics: string; // "45M, Walk-in"
    complaint: string;    // structured chief complaint
  };

  /** Triage Agent — assigns an ATS category with reasoning. */
  triageAgent?: {
    category: TriageCategory;
    categoryName: string;    // e.g. "Emergency"
    reasoning: string;       // why this category was chosen
    keySymptoms: string[];   // tags shown as pills in PatientFlow panel
  };

  /** Nurse Agent — reviews vitals, flags abnormals, places initial orders. */
  nurseAgent?: {
    vitalsAssessment: string;  // narrative assessment
    abnormalFlags: string[];   // e.g. ["Tachycardia", "Low SpO2"]
    ordersPlaced: string[];    // nursing actions e.g. ["IV access", "ECG"]
    labsOrdered: string[];     // blood tests ordered
  };

  /** Doctor Agent — forms a differential diagnosis and clinical picture. */
  doctorAgent?: {
    clinicalPicture: string;         // narrative clinical assessment
    differentialDiagnosis: string[]; // ranked list; index 0 = most likely
    reasoning: string;               // justification for top diagnosis
  };

  /** Decision Agent — final disposition with confidence probabilities. */
  decisionAgent?: {
    disposition: DispositionLabel;
    confidence: number;   // 0–1 (e.g. 0.89 = 89%)
    probabilities: {
      admit: number;
      shortStay: number;
      discharge: number;
    };
    rationale: string;   // human-readable justification for the decision
  };
}

/**
 * Runtime state for a single agent card shown in the Pipeline panel.
 * The thinkingText cycles through pre-defined messages during animation.
 */
export interface AgentState {
  id: keyof AgentOutputMap;
  name: string;
  role: string;
  status: AgentStatus;
  thinkingText?: string; // displayed in the active "thinking" bubble
}

/**
 * A single timestamped entry in the EMR Live Log panel.
 * Entries are generated by the UI animation — not by the AI directly.
 */
export interface EMREntry {
  id: string;
  ts: string;                          // HH:MM:SS timestamp
  agent: string;                       // human-readable agent name
  agentId: keyof AgentOutputMap;       // used to colour the agent label
  message: string;
  type: 'info' | 'action' | 'result' | 'warning';
  // info    — grey dot  — status messages
  // action  — blue dot  — italicised thinking steps
  // result  — green dot — bold agent output summary
  // warning — orange    — error / abnormal flag
}
